version: '2.2'
services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: elasticsearch/
      args:
        - ELK_VERSION
    environment: 
      - ES_JAVA_OPTS
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - esdata:/usr/share/elasticsearch/data
    ports: 
      - 9200:9200
    networks: 
      - esnet

  logstash:
    container_name: logstash
    build:
      context: logstash/
      args: 
        - ELK_VERSION
    depends_on:
      - elasticsearch
      - kafka
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./avro/schema.avsc:/usr/share/avro/schema.avsc:ro
    ports:
      - 5000:5000
      - 9600:9600
    environment:
      - LS_JAVA_OPTS
    networks:
      - esnet

  kibana:
    container_name: kibana
    build:
      context: kibana/
      args:
        - ELK_VERSION
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - esnet

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      - esnet

  kafka:
    container_name: kafka
    build:
      context: kafka/
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: $KAFKA_ADVERTISED_HOST_NAME
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - esnet

volumes:
  esdata:
    driver: local

networks:
  esnet:
