version: '2.2'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      - esnet

  kafka:
    container_name: kafka
    build:
      context: kafka/
      args:
        - KAFKA_VERSION
    depends_on:
      - zookeeper
    ports:
      - $KAFKA_PORT:$KAFKA_PORT
    environment:
      KAFKA_PORT: $KAFKA_PORT
      KAFKA_ADVERTISED_HOST_NAME: $KAFKA_HOST
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - esnet

  elasticsearch:
    container_name: elasticsearch
    build:
      context: elasticsearch/
      args:
        - ELK_VERSION
    environment: 
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - esdata:/usr/share/elasticsearch/data
    ports: 
      - 9200:9200
    networks: 
      - esnet

  logstash:
    container_name: logstash
    build:
      context: logstash/
      args: 
        - ELK_VERSION
    depends_on:
      - elasticsearch
      - kafka
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ${SCHEMA_PATH}:/usr/share/schema.avsc:ro
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    networks:
      - esnet

  kibana:
    container_name: kibana
    build:
      context: kibana/
      args:
        - ELK_VERSION
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - esnet

  python-consumer:
    container_name: python-consumer
    build: python/
    depends_on:
      - kafka
    environment:
      - KAFKA_HOST
      - KAFKA_PORT
      - KAFKA_TOPIC
    volumes:
      - ./python/consumer.py:/home/consumer.py
      - ${SCHEMA_PATH}:/usr/share/schema.avsc:ro
    tty: true

  python-producer:
    container_name: python-producer
    build: python/
    depends_on:
      - python-consumer
    environment:
      - KAFKA_HOST
      - KAFKA_PORT
      - KAFKA_TOPIC
    volumes:
      - ./python/producer.py:/home/producer.py
      - ${SCHEMA_PATH}:/usr/share/schema.avsc:ro
    tty: true

volumes:
  esdata:
    driver: local

networks:
  esnet:
